name: kitap_takas
description: Kitap takas uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.15.3
  mobile_scanner: ^3.5.5
  http: ^1.1.0
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  google_books_api: ^1.0.0
  file_picker: ^6.1.1
  csv: ^5.1.1
  flutter_chips_input: ^1.9.0
  flutter_slidable: ^3.0.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 